name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter pub get

      # تعديل الـ base-href ليتوافق مع اسم المستودع الحالي
      - run: flutter build web --release --base-href "/aksab_admin/" --no-wasm-dry-run

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          # شلنا الـ CNAME عشان نعتمد على رابط جيت هب مؤقتاً
